language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

matrix:
  include:
    - python: "3.7"
      dist: xenial
    - python: "pypy3.5"
      dist: xenial

before_install:
  - pip install --upgrade pip
  - pip install poetry
  - pip install coverage
  - pip install coveralls

install:
  - poetry install

script:
  - poetry run coverage run --source=pypika -m unittest discover -b

after_success:
  coveralls

before_deploy:
  # User and password environment variables are set as hidden variables through
  # the web interface in the project settings.
  - pip install --upgrade pip
  - pip install poetry
  - poetry config http-basic.pypi $PYPI_USER $PYPI_PASS
  - poetry build

deploy:
  provider: script
  script: poetry publish
  on:
    tags: true


