language: python

python:
    - "3.5"
    - "3.6"
    - "3.7"

matrix:
  include:
  - python: "3.7"
    dist: xenial
  - python: "pypy3.5"
    dist: xenial

install:
    - "poetry install"
    - "pip install coverage"
    - "pip install coveralls"
    - "pip install parameterized==0.7.0"

script:
    - "coverage run --source=poetry run test"

after_success:
    coveralls
